# version: '3.8'

services:
  
  mi-app-web:
    image: python:3.11-slim
    working_dir: /app
    
    # --- ¡CAMBIO IMPORTANTE! ---
    # Ya no montamos el código fuente (¡esto es "producción"!)
    # En su lugar, montamos nuestro "disco duro" llamado 'datos-db'
    # en la carpeta '/data' que definimos en Flask.
    volumes:
      - datos-db:/data  # 1. Nuestro "disco duro" para la base de datos
      - .:/app           # 2. El "portal mágico" para el código
      
    command: >
      sh -c "pip install -r requirements.txt && 
             python 22-app-flask.py"
    ports:
      - "5001:5001"
      
    # ¡NUEVO! Tenemos que "construir" la imagen
    # cada vez, porque ya no leemos los archivos locales.
    build: . 

  mi-dashboard:
    # (¡Este se queda igual, no necesita datos permanentes!)
    image: python:3.11-slim
    working_dir: /app
    volumes:
      - .:/app # Lo dejamos en modo "desarrollo"
    command: >
      sh -c "pip install -r requirements.txt && 
             streamlit run 23-dashboard.py --server.port 8501 --server.address 0.0.0.0"
    ports:
      - "8501:8501" 
      
# --- ¡DEFINIMOS EL "DISCO DURO"! ---
# Le decimos a Docker: "Oye, crea un volumen llamado 'datos-db'"
volumes:
  datos-db: